name: Weather App

# Trigger workflow on every push to main branch or pull request to main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Pulls code from the GitHub repository

    - name: Setup Node.js
      uses: actions/setup-node@v4 # Sets up Node.js in the runner
      with:
        node-version: '18' # Specify the version the project uses

    - name: Install dependencies
      run: npm ci # Installs exact versions from package-lock.json for consistency

    # - name: Run tests
    #   run: npm test # Runs tests defined in the project

    - name: Build project
      run: npm run build # Builds the Vite React project

    - name: Deploy to Render
      if: success()
      run: curl x POST "${{ secrets.RENDER_EXTERNAL_WEBHOOK_URL }}"